In [4]:
import os
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as pl
import shutil

In [ ]:

hcc_retro_pro = pd.read_excel('/Users/Francisco/Desktop/RestrepoProjects/Regeneron retrospective radiomics/databases/HCC_radiomics_Regeneron_database.xlsx',sheet_name='SA1')
parissa = pd.read_excel('/Users/Francisco/Desktop/RestrepoProjects/Regeneron retrospective radiomics/databases/HCC_radiomics_Regeneron_database.xlsx',sheet_name='Parissa Source')
vivek_new1 = pd.read_excel('/Users/Francisco/Desktop/RestrepoProjects/Regeneron retrospective radiomics/databases/Vivek_HCC_cases.xlsx')
vivek_new1 = vivek_new1.drop_duplicates(subset='MRN')

v_in_hcc = vivek_new1.loc[vivek_new1['MRN'].isin(hcc_retro_pro['MRN']), :]
v_in_hcc

,Name,MRN,Accession,Date of imaging,Contrast,T1 Pre,T1 AP (1/2),T1 PVP,T1 TP,T1 HBP,Comment
2,"ORTIZ,HECTOR",7058928,5885449,2011-11-15,EOB,NaN,NaN,NaN,NaN,NaN,MISSING FROM VIEWER
3,"DONG, RUI",4460240,Outside,2018-10-28,EOB,T1_VIBE_AX_PRE,T1_VIBE_AX_POST_1,T1_VIBE_AX_POST_3,T1_VIBE_AX_POST_4,T1_VIBE_AX_POST_ABD_DELAY,NaN
4,"HARTLEY, ZIPPORA",1818521,100670487,2019-01-18,EOB,Ax_LAVA-XV_PRE__2-PHASE_20_SEC_1_MIN_2MIN_3_MIN,Ph2Ax_LAVA-XV_PRE__2-PHASE_20_SEC_1_MIN_2MIN_3...,Ph3Ax_LAVA-XV_PRE__2-PHASE_20_SEC_1_MIN_2MIN_3...,Ph5Ax_LAVA-XV_PRE__2-PHASE_20_SEC_1_MIN_2MIN_3...,Ax_LAVA-XV_20_MIN_DELAY,NaN
5,"DINGLE, KERMIT T",2847676,1001282594,2018-09-28,EOB,NaN,NaN,NaN,NaN,NaN,MISSING FROM VIEWER
6,"MILLER, MANYA",887519,100434437,2018-10-11,EOB,T1_VIBE_PRE-CAIPI,T1_VIBE_POST-CAIPI_003,T1_VIBE_POST-CAIPI_1_min,T1_VIBE_POST-CAIPI_3_min,T1_VIBE_POST-CAIPI_20_min,NaN
...,...,...,...,...,...,...,...,...,...,...,...
174,"Gao, Yun",9111333,outside study,2017-12-09,EOB,t1_vibe_fs_tra,t1_vibe_fs_tra_3_post_004,t1_vibe_fs_tra_3_post,t1_vibe_fs_tra_3_post_001,t1_vibe_fs_tra_20_MIN,NaN
175,"Estama,Rosemarie",8193718,1000756323,2017-12-01,EOB,se-THRIVES_dyn_BH1,se-THRIVES_dyn_BH2,se-THRIVES_dyn_BH3,se-THRIVES_dyn_BH4,mDIXON_Hepatobiliary_20_min_30_flip,NaN
176,"Park, Sue",8697658,outside study,2018-02-02,EOB,T1_VIBE_AX_PRE,T1_VIBE_AX_POST_1,T1_VIBE_AX_POST_4_003,T1_VIBE_AX_POST_4,T1_FS_2D_DELAY_AX,NaN
177,Abdourahamane Sow,E104782,outside study,2018-03-11,EOB,T1_Vibe_AX_Pre,T1_Vibe_AX_POST_2,T1_Vibe_AX_POST_3,T1_Vibe_AX_POST_4,T1_Vibe_AX_Post_Delay,NaN
178,Samir Boctor-Girgis,8343543,9709904,2018-04-25,EOB,T1_VIBE_PRE-CAIPI,T1_VIBE_POST-CAIPI_002,T1_VIBE_POST-CAIPI,T1_VIBE_POST-CAIPI_4,T1_VIBE_POST-CAIPI_20_min,NaN

In [11]:

hcc_retro_pro

,Data Source,"Cohort, if known (e.g. Regeneron Cemiplimab prospective)",MRN,First name,Last name,Date of MRI exam,MRI Accession number,Indication for MRI exam,Etiology of liver disease,Cirrhosis,...,Tumor stage,Histopathologic characteristics (comments from the report ),TILs,TLS,HCC recurrence within 2 years (yes/no),First Imaging Date of Recurrence,Time to Recurrence (days),Time of Latest Followup (For No Recurrence),Time to Follow Up (For No Recurrence),Recurrence Comments
0,HCC_database_retrospective_prospective (n=81),Retrospective,A153278,James,Blackman,2018-06-07 00:00:00,100146095,HCV cirrhosis with new 2.5 cm segment 5/6 mass.,HCV,Y,...,pT1bNX,"Fibrosis, periportal and perivenular with thin...",NaN,NaN,N,NaN,NaN,2022-12-08,1632.0,NaN
1,HCC_database_retrospective_prospective (n=81),Retrospective,E111274,Thomas,Saunders,2018-07-27 00:00:00,100268631,HCV cirrhosis status post Harvoni (4/2018),"HCV, MASH",Y,...,pT2NX,Steatohepatitic and glandular,NaN,NaN,N,NaN,NaN,2022-09-23,1502.0,NaN
2,HCC_database_retrospective_prospective (n=81),Retrospective,3078096,Hui Sheng,Ma,2018-10-02 00:00:00,S0000568131,HCC,HBV,Y,...,rpT2NX,"Heterogeneous, chronic hepatitis B, mild steat...",NaN,NaN,N,NaN,NaN,2022-02-09,1213.0,"Recurrent post 2-years HCC, segments 7, 8 recu..."
3,HCC_database_retrospective_prospective (n=81),Retrospective,2847676,Kermit T,Dingle,2018-09-28 00:00:00,1001282594,Hepatitis C. Liver lesion on ultrasound. Evalu...,HCV,Y,...,pT1bNX,NaN,NaN,NaN,N,NaN,NaN,2024-11-11,2163.0,NaN
4,HCC_database_retrospective_prospective (n=81),Retrospective,887519,Manya,Miller,2018-10-11 00:00:00,100434437,HCV cirrhosis. 3.5 cm left hepatic lobe lesion...,"HCV, MASH",Y,...,pT1bNX,NaN,NaN,NaN,N,NaN,NaN,2024-09-25,2150.0,Recurrent post 2-years HCC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,HCC resections 2010-present Parissa 10-9-2023 ...,NaN,5675297,John,McPartland,2020-11-06 00:00:00,1004201619,HCC lesion short-term monitoring,"MAFLD, HCV",Y,...,pT1aNX,NaN,NaN,NaN,N,NaN,NaN,2023-12-08,1093.0,"Recurrence post 2 years, 2 LIRADS 5 lesions 1...."
117,HCC resections 2010-present Parissa 10-9-2023 ...,NaN,F118116,Elsaid,Sharara,2020-11-16 00:00:00,1004397003,HCC,HCV,Y,...,pT2NX,NaN,NaN,NaN,Y,2022-02-15 00:00:00,447.0,NaT,NaN,"Recurrence in segment 4, infiltrative appearin..."
118,HCC resections 2010-present Parissa 10-9-2023 ...,NaN,7504204,Inocencia,Morales,2020-09-22 00:00:00,1004134762,NaN,"Unknown, hepatomegaly",N,...,pT4N0,"Poorly differentiated HCC, intraoperative tumo...",NaN,NaN,Y,2020-11-18 00:00:00,50.0,NaT,NaN,"Left lower lobe nodule, right upper lobe nodul..."
119,HCC resections 2010-present Parissa 10-9-2023 ...,NaN,E361405,Miller,Gilbert,2020-05-08 00:00:00,"EXAM CKEY: 17078109, UNIQUE EXAM ID: 001I44D12...",gh,HCV,Y,...,pT1bNX,NaN,NaN,NaN,Y,2021-02-10 00:00:00,272.0,NaT,NaN,Recurrent HCC
120,Sequence_Match Vivek 01-22-2025 (n=179),NaN,8333176,Karimu,Yorose,2018-08-20 00:00:00,"EXAM CKEY: 14639019, UNIQUE EXAM ID: 001I44D04...",Abdominal pain,HBV,N,...,pT3NX,NaN,NaN,NaN,Y,2019-06-24 00:00:00,263.0,NaT,NaN,"Segment 5, 6/7, 8 recurrence"

In [99]:
v1_not_in_v2 = vivek_new1.loc[~vivek_new1['MRN'].isin(vivek_new2['name']), :]
v1_not_in_v2

,Unnamed: 0,user_id,study_name,MRN,name,group_id,color,z,dcm_name,points_array
0,0,11,DL HCC T2 and DWI,1611495,AX_T2_SSFSE_BH,temp,#FFFF00,28,IM_029.dcm,"[104.60689655172413, 103.28275862068965, 104.1..."
4,4,11,DL HCC T2 and DWI,1818521,Ax_SSFSE_BH_LONG_TE,temp,#FFFF00,51,IM_052.dcm,"[143.00689655172414, 214.5103448275862]"
11,11,11,DL HCC T2 and DWI,1963735,T2_HASTE_AX,temp,#FFFF00,15,IM_016.dcm,"[76.35862068965517, 94.01379310344828]"
14,14,11,DL HCC T2 and DWI,2120572,AX_T2_SSFSE,temp,#FFFF00,12,IM_013.dcm,"[102.4, 142.12413793103448, 101.51724137931035..."
16,16,11,DL HCC T2 and DWI,2783615,DIFFUSION_NW2_NR,temp,#FFFF00,12,IM_013.dcm,"[54.62068965517241, 69.84827586206896, 53.9586..."
...,...,...,...,...,...,...,...,...,...,...
717,717,11,DL HCC T2 and DWI,9111333,T2_AX_80_TE,temp,#FFFF00,16,IM_017.dcm,"[135.17241379310346, 51.310344827586206, 135.1..."
725,725,11,DL HCC T2 and DWI,E104782,T2_Haste_Axial,temp,#ffff00,38,IM_039.dcm,"[69.29655172413793, 74.59310344827587, 68.8551..."
741,741,11,DL HCC T2 and DWI,E159825,T2_AX_80_TE,temp,#FFFF00,19,IM_020.dcm,"[63.44827586206897, 182.06896551724137, 62.896..."
747,747,11,DL HCC T2 and DWI,E376152,AX_T2_MVXD,temp,#ffff00,39,IM_040.dcm,"[115.08965517241379, 223.22758620689655, 115.0..."
765,765,11,DL HCC T2 and DWI,E390376,AX_HASTE_T2_Long_TE,temp,#FFFF00,21,IM_022.dcm,"[87.39310344827587, 92.6896551724138, 86.95172..."

In [10]:
# Intersection with cases analyzed by Valentin and Amine

val1 = pd.read_excel('/Users/Francisco/Desktop/RestrepoProjects/Regeneron retrospective radiomics/databases/amine_valentin_radiomics/DLHCC_T2&DWI_data_all_rois.xlsx')
nate = pd.read_excel('/Users/Francisco/Desktop/RestrepoProjects/Regeneron retrospective radiomics/databases/cases_01_27_25/nate_mrns_01_27_25.xlsx')

val1_in_nate = nate.loc[nate['MRN'].isin(val1['name']), :]
val1_in_nate

,MRN,First name,Last name,Date of MRI exam,MRI Accession number,Notes,Eovist
16,7240028,Bronya,Sadomskaya,2013-02-27 00:00:00,6543091,NaN,NaN
18,7324501,Lynwood,Jones,2013-10-30 00:00:00,6945042,NaN,NaN
19,6551793,Robert,Lucas,2013-12-04 00:00:00,6986522,NaN,NaN
23,7170205,Thomas,Marvelli,2014-05-13 00:00:00,7242966,NaN,NaN
24,7399742,Xing,Li,2014-05-31 00:00:00,7263665,NaN,NaN
30,7587555,Ramon,Grajo,2015-01-07 00:00:00,7622647,NaN,NaN
31,3878246,Gaafar,Abada,2015-01-14 00:00:00,7626643,NaN,NaN
32,7613206,Fortunato,Pellicano,2015-03-04 00:00:00,7705618,NaN,NaN
35,7657378,Spencer,Wissinger,2015-04-29 00:00:00,7811170,NaN,NaN
37,6579945,Edward,Hutchinson,2015-07-03 00:00:00,7903773,NaN,NaN
40,761566,Brenda,Sanchez,2015-11-11 00:00:00,8155300,NaN,NaN
41,2909144,Virginia,Porcell,2015-12-23 00:00:00,8232177,NaN,NaN
43,1611495,Craig,Lazar,2016-03-28 00:00:00,8391720,NaN,NaN
46,2822689,Lujing,Wang,2016-12-30 00:00:00,8897828,NaN,NaN
49,9049165,Min,Chen,2017-04-28 00:00:00,9141831,NaN,NaN
51,8343543,Samir,Boctor-Girgis,2018-04-25 00:00:00,9709904,NaN,NaN
58,1818521,Zippora,Hartley,2018-11-27 00:00:00,100554071,NaN,NaN
59,3252913,Ana,Rodriguez,2019-01-02 00:00:00,100633251,NaN,NaN
61,E390376,James,Weeks,2019-02-25 00:00:00,100765802,NaN,NaN
70,8193718,Rosemarie,Estama,2017-12-01 00:00:00,1000756323,NaN,NaN
71,8118110,Rogelio,Pronstroller,2018-06-12 00:00:00,1001091520,NaN,NaN
90,9054960,John,Baris,2017-04-26 00:00:00,"EXAM CKEY: 11987294, UNIQUE EXAM ID: 001I44D04...",Outside exam,Yes
91,5546735,Mario,Albano,2017-06-23 00:00:00,"EXAM CKEY: 12230486, UNIQUE EXAM ID: 001I44D04...",Outside exam,GAD
92,9069414,Xujie,Hu,2017-07-03 00:00:00,"EXAM CKEY: 12381313, UNIQUE EXAM ID: 001I44P14...",Outside exam,Yes
93,9068259,Subhash,Shah,2017-06-28 00:00:00,"EXAM CKEY: 12382205, UNIQUE EXAM ID: 001I44P14...",Outside exam,Yes
94,9089954,Suiquan,Wen,2017-09-21 00:00:00,"EXAM CKEY: 12718769, UNIQUE EXAM ID: 001I44D04...",Outside exam,Yes
96,9081737,Jose,Lopez,2017-10-27 00:00:00,"EXAM CKEY: 12823730, UNIQUE EXAM ID: 001I44D04...",Outside exam,Yes
97,8697658,Sue,Park,2018-02-02 00:00:00,"EXAM CKEY: 13636101, UNIQUE EXAM ID: 001I44D04...",Outside exam,Yes
98,E104782,Abdourahamane,Sow,2018-03-11 00:00:00,"EXAM CKEY: 13896070, UNIQUE EXAM ID: 001I44P14...",Outside exam,Yes
99,3811071,Manuel,Ras,2018-05-21 00:00:00,"EXAM CKEY: 14280673, UNIQUE EXAM ID: 001I44D04...",Outside exam,Yes
104,4460240,Rui,Dong,2018-10-28 00:00:00,"EXAM CKEY: 14904797, UNIQUE EXAM ID: 0001I44P1...",Outside exam,Yes
105,E376152,Jian,Zheng,2018-12-28 00:00:00,EXAM CKEY: 15099394; UNIQUE EXAM ID: 001I44D04...,Outside exam/strange series names/poor quality,NaN
107,9109448,Jianwu,Fan,2017-12-09 00:00:00,"EXAM CKEY: 15139228, UNIQUE EXAM ID: 001I44D04...",Outside exam,Yes
108,9111333,Yun,Gao,2017-12-09 00:00:00,"EXAM CKEY: 15251866, UNIQUE EXAM ID: 001I44D04...",Outside exam,Yes
117,9035717,Roger,Lin,2017-02-15 00:00:00,"EXAM CKEY: 8754274, UNIQUE EXAM ID: 001I44D041...",Outside exam,Yes
118,4340672,Young,Chung,2017-02-23 00:00:00,"EXAM CKEY: 8924004, UNIQUE EXAM ID: 001I44D043...",Outside exam,Yes